<?php
declare(strict_types=1);

namespace Tests\Unit\src\Infrastructure\Persistence\Eloquent;

use App\Models\PointModel;
use App\src\Application\DTO\PointDto;
use App\src\Infrastructure\Persistence\Eloquent\PointRepositoryEoloquent;
use Mockery;
use Tests\TestCase;

class PointRepositoryEoloquentTest extends TestCase
{

    protected PointModel $pointModel;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->pointModel = Mockery::mock(PointModel::class);
        $this->pointModel
            ->shouldReceive('create')
            ->andReturn($this->pointModel);
    }

    public function testCreateSuccess()
    {
        $mockPointDto = PointDto::fromArray([
            'uuid' => 'mock-mock-mock-mock',
            'name' => 'test',
            'latitude' => 15,
            'longitude' => 30,
            'open_hour' => '08:17',
            'close_hour' => '18:21',
        ]);

        $pointRepository = new PointRepositoryEoloquent();
        $point = $pointRepository->create($mockPointDto);

        $this->assertInstanceOf(PointDto::class, $point);
    }
}
