<?php
namespace Tests\Unit\src\Domain\Services;

use App\src\Application\DTO\PointDto;
use App\src\Domain\Cache\CacheInterface;
use App\src\Domain\Repositories\PointRepositoryInterface;
use App\src\Domain\Services\PointsService;
use Mockery;
use Tests\TestCase;

class PointsServiceTest extends TestCase
{
    protected PointRepositoryInterface $pointRepository;
    protected CacheInterface $cache;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->pointRepository = Mockery::mock(PointRepositoryInterface::class);
        $this->pointRepository
            ->shouldReceive('create')
            ->andReturn(PointDto::fromArray([
                'uuid' => 'mock-mock-mock-mock',
                'name' => 'test',
                'latitude' => 15,
                'longitude' => 30,
                'open_hour' => '08:17',
                'close_hour' => '18:21',
            ]));

        $this->cache = Mockery::mock(CacheInterface::class);
        $this->cache
            ->shouldReceive('delete')
            ->andReturn(true);
        $this->cache
            ->shouldReceive('get')
            ->andReturn(null);
    }

    public function testCreateSuccess()
    {
        $pointDto = PointDto::fromArray([
            'uuid' => 'mock-mock-mock-mock',
            'name' => 'test',
            'latitude' => 15,
            'longitude' => 30,
            'open_hour' => '08:17',
            'close_hour' => '18:21',
        ]);

        $pointsService = new PointsService($this->pointRepository, $this->cache);
        $point = $pointsService->create($pointDto);

        $this->assertEquals('mock-mock-mock-mock', $point->uuid);
    }

    public function testCreateException()
    {
        $pointDto = PointDto::fromArray([
            'uuid' => 'mock-mock-mock-mock',
            'name' => 'test',
            'latitude' => 15,
            'longitude' => 30,
            'open_hour' => '08:17',
            'close_hour' => '18:21',
        ]);

        $this->pointRepository
            ->shouldReceive('create')
            ->andThrow(new \Exception('Error'));

        $pointsService = new PointsService($this->pointRepository, $this->cache);

        $this->expectException(\Exception::class);
        $pointsService->create($pointDto);
    }

    public function testGetPointSuccess()
    {
        $points = [
            PointDto::fromArray([
                'uuid' => 'mock-mock-mock-mock',
                'name' => 'test',
                'latitude' => 15,
                'longitude' => 30,
                'open_hour' => '08:17',
                'close_hour' => '18:21',
            ]),
            PointDto::fromArray([
                'uuid' => 'mock-mock-mock-mock',
                'name' => 'test',
                'latitude' => 15,
                'longitude' => 30,
                'open_hour' => '08:17',
                'close_hour' => '18:21',
            ]),
        ];

        $this->pointRepository
            ->shouldReceive('all')
            ->andReturn($points);

        $this->cache
            ->shouldReceive('set')
            ->andReturn(true);

        $pointsService = new PointsService($this->pointRepository, $this->cache);
        $point = $pointsService->getPoints();

        $this->assertEquals(2, count($point));
    }
}
