<?php
namespace Tests\Unit\src\Application\Actions;

use App\src\Application\Actions\DeletePointAction;
use App\src\Application\Actions\ListPointsAction;
use App\src\Application\DTO\PointDto;
use App\src\Domain\Services\PointsService;
use Tests\TestCase;

class DeletePointActionTest extends TestCase
{
    protected PointsService $pointsService;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->pointsService = $this->createMock(PointsService::class);
        $this->pointsService
            ->method('delete')
            ->willReturn(true);
    }

    /**
     * @throws \Exception
     */
    public function testExecuteDeleteSuccess()
    {
        $mockuuidPointDto = 'mock-mock-mock-mock';
        $listPointsAction = new DeletePointAction($this->pointsService);
        $result = $listPointsAction->execute($mockuuidPointDto);

        $this->assertTrue($result);
    }
}
