<?php
namespace Tests\Unit\src\Application\Actions;

use App\src\Application\Actions\CreatePointAction;
use App\src\Application\Actions\ListPointsAction;
use App\src\Application\DTO\PointDto;
use App\src\Domain\Services\PointsService;
use Tests\TestCase;

class LisPointsActionTest extends TestCase
{
    protected PointsService $pointsService;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->pointsService = $this->createMock(PointsService::class);
        $this->pointsService
            ->method('getPoints')
            ->willReturn([
                PointDto::fromArray([
                    'uuid' => 'mock-mock-mock-mock',
                    'name' => 'Test',
                    'latitude' => 30,
                    'longitude' => 50,
                    'open_hour' => '08:15',
                    'close_hour' => '18:00',
                ])
            ]);
    }

    public function testExecuteSuccess()
    {
        $listPointsAction = new ListPointsAction($this->pointsService);
        $result = $listPointsAction->execute();

        $this->assertIsArray($result);
    }
}
